config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  get 'home/demo', to: 'home#demo'
  get '/privacy', to: 'home#privacy'
  get 'feed',:to=>'home#feed'

  # Admin 인증 라우트
  devise_for :admins,
             class_name: 'User',
             path: 'admins',
             path_names: {
               sign_in: 'login',
               sign_out: 'logout'
             },
             controllers: {
               sessions: 'admins/sessions'
             }

  namespace :admin do
    root to: 'home#index'

    resources :contacts
    resources :users
    resources :blogs
    resources :notices
    resources :histories
    resources :galleries
  end

  devise_for :users, :controllers => { :sessions => "users/sessions",:registrations => "users/registrations" }, :path_names =>  {:sign_up=>'new',:sign_in => 'login', :sign_out => 'logout'}

  devise_scope :user do
    get '/login', to: 'users/sessions#new', as: :login_redirect
    delete '/logout', to: 'users/sessions#destroy', as: :logout_redirect
  end

  resources :intro, :galleries, :blogs, :notices, :locations, :histories, :contacts

end

app/models/notice.rb
class Notice < ActiveRecord::Base
  is_impressionable
  has_rich_text :content
  validates_presence_of :title
  validates_length_of :title, minimum: 4, maximum: 60
  belongs_to :user, :autosave=>true
end

app/controllers/admin/notices_controller.rb
class Admin::NoticesController < Admin::AdminController
  before_action :set_notice, only: [:show, :edit, :update, :destroy]

  # GET /notices
  # GET /notices.json
  def index
    params[:per_page] = 10 unless params[:per_page].present?

    @notice_count = Notice.count
    @notices = Notice.page(params[:page]).per(params[:per_page]).order('id desc')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @notices }
    end
  end

  # GET /notices/1
  # GET /notices/1.json
  def show
  end

  # GET /notices/complete
  def new
    @notice = Notice.new
  end

  # GET /notices/1/edit
  def edit
  end

  # POST /notices
  # POST /notices.json
  def create
    @notice = Notice.new(notice_params)

    respond_to do |format|
      if @notice.save
        format.html { redirect_to [:admin, @notice], notice: t(:notice, scope: [:activerecord, :models])+t(:message_success_create) }
        format.json { render :show, status: :created, location: @notice }
      else
        format.html { render action: 'new' }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notices/1
  # PATCH/PUT /notices/1.json
  def update
    respond_to do |format|
      if @notice.update(notice_params)
        format.html { redirect_to [:admin, @notice], notice: t(:notice, scope: [:activerecord, :models])+t(:message_success_update) }
        format.json { render :show, status: :ok, location: @notice }
      else
        format.html { render action: 'edit' }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notices/1
  # DELETE /notices/1.json
  def destroy
    @notice.destroy
    respond_to do |format|
      format.html { redirect_to admin_notices_url }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_notice
    @notice = Notice.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def notice_params
    params.require(:notice).permit(:title, :popup, :enable, :content).merge(user_id: current_user.id)
  end
end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController
  impressionist :actions => [:show]
  before_action :authenticate_user!, :except => [:index,:show]
  before_action :set_notice, only: [:show, :edit, :update, :destroy]

  def initialize(*params)
    super(*params)

    @application_name=t(:application_name)
    @controller_name= t(:notice, scope: [:activerecord, :models])
    @title=@controller_name
  end
  # GET /notices
  # GET /notices.json
  def index
    if params[:search_detail].present?
      session[:search_detail]=1
    else
      if params[:search_summary].present?
        session.delete(:search_detail)
      end
    end

    if params[:list_type].present?
      if params[:list_type]=='list'
        session[:notice_list_type]='list'
      else
        session[:notice_list_type]='module'
      end
    end


    condition = { enable: true }

    @notice_count = Notice.where(condition).count
    @notices = Notice.where(condition).page(params[:page]).per(params[:per_page]).order('id desc')


    respond_to do |format|
      format.html # _slide.html.erb
      format.json { render json: @notices }
    end
  end

  # GET /notices/1
  # GET /notices/1.json
  def show
  end

  # GET /notices/complete
  def new
    @notice = Notice.new
  end

  # GET /notices/1/edit
  def edit
  end

  # POST /notices
  # POST /notices.json
  def create
    @notice = Notice.new(notice_params)

    respond_to do |format|
      if @notice.save
        format.html { redirect_to [ @notice], notice: t(:notice, scope: [:activerecord, :models])+t(:message_success_create) }
        format.json { render :show, status: :created, location: @notice }
      else
        format.html { render action: 'new' }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notices/1
  # PATCH/PUT /notices/1.json
  def update
    respond_to do |format|
      if @notice.update(notice_params)
        format.html { redirect_to [ @notice], notice: t(:notice, scope: [:activerecord, :models])+t(:message_success_update) }
        format.json { render :show, status: :ok, location: @notice }
      else
        format.html { render action: 'edit' }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /notices/1
  # DELETE /notices/1.json
  def destroy
    @notice.destroy
    respond_to do |format|
      format.html { redirect_to admin_notices_url }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_notice
    @notice = Notice.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def notice_params
    params.require(:notice).permit(:title, :popup, :enable, :content).merge(user_id: current_user.id)
  end
end

app/views/notices/_form.html.erb
<div class="col-12">
  <%= form_with(model: notice, local: true) do |form| %>
    <% if notice.errors.any? %>
      <div id="error_explanation" class="alert alert-danger">
        <a href="#" class="close" data-dismiss="alert">&times;</a>
        <h2><%= pluralize(notice.errors.count, "error") %> prohibited this request from being saved:</h2>
        <ul>
          <% notice.errors.full_messages.each do |msg| %>
            <li>
              <%= msg %>
            </li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="form-row">
      <article class="col-12">
        <div class="card">
          <div class="card-body">
            <div class="form-row">
              <div class="col-12 form-group">
                <%= form.label :notice_category_id, :class => 'control-label' %>
                <%= form.select :notice_category_id, options_from_collection_for_select(BlogCategory.where(:enable => true), 'id', 'title', @notice.notice_category_id), {}, { :class => "form-control input-lg" } %>
              </div>
            </div>

            <div class="form-row">
              <div class="col-12 form-group">
                <%= form.label :title, :class => 'control-label' %>
                <%= form.text_field :title, {:class => "form-control"} %>
              </div>
              <div class="col-12 form-group">
                <%= form.fields_for :notice_picture  do |pp| %>
                    <%= pp.label :picture %>
                    <%= pp.file_field :picture, :class => "form-control-file" %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </article>
      <div class="col-12 form-group">
        <h3><%= form.label :content %></h3>
        <%= form.rich_text_area :content, style: 'min-height:20em' %>
      </div>
      <div class="d-grid gap-2">
        <%= form.submit :class => 'btn btn-lg btn-primary' %>
      </div>
    </div>
  <% end %>
</div>

app/views/notices/_index.html.erb
<article id="sl_main_notice" class="col-12">
  <h3><%=t('activerecord.models.notice') %></h3>
  <ul>
    <% unless @notices.empty? %>
      <% @notices.each do |notice| %>
        <li>
          <%= link_to notice.title, notice  %>
          <span class="d-none d-lg-block text-muted" style="float:right;"><%=time_ago_in_words notice.created_at.to_date %></span>
        </li>
      <% end %>
    <% else %>
      <li><%=t(:no_data) %></li>
    <% end %>
  </ul>
  <%=link_to t(:link_more),notices_path,:class=>'more' %>
</article>

app/views/notices/_index_default.html.erb
<section class="row">
  <% unless @notice_count.zero? %>
    <% @notices.each do |notice| %>
      <%=render 'index_media',notice: notice %>
    <% end %>
    <div class="col-12">
      <%= paginate @notices %>
    </div>
  <% else %>
    <div class="notice col-12">
      <%= t(:no_data) %>
    </div>
  <% end %>
  <% if admin_signed_in? %>
  <div class="col-12">
    <%=link_to t(:link_new),new_notice_path,class: 'btn btn-primary btn-large' %>
  </div>
    <% end %>
</section>

app/views/notices/_index_list.html.erb
<div class="row">
  <div class="col-12">
    <div id="blog-main" class="table-responsive">
      <table class="table table-striped sl-table">
        <colgroup>
          <col>
          <col>
          <col>
          <col>
        </colgroup>
        <thead class="thead-default">
        <tr>
          <th><%= t(:user_id, scope: [:activerecord, :attributes, :notice]) %></th>
          <th><%= t(:title, scope: [:activerecord, :attributes, :notice]) %></th>
          <th class="text-end"><%= t(:label_count) %></th>
          <th class="text-end"><%= t(:created_at, scope: [:activerecord, :attributes, :notice]) %></th>
        </tr>
        </thead>
        <tbody>
        <% unless @notice_count.zero? %>
          <% @notices.each do |notice| %>
            <tr>
              <td><%=display_user_photo(notice.user) %>&nbsp;&nbsp;<%= notice.user.nickname.truncate_bytes(16) %></td>

              <td><%= link_to notice.title, notice %></td>
              <td class="text-end"><%= notice.impressionist_count(:filter => :ip_address) %></td>
              <td class="text-end text-secondary"><%= time_ago_in_words notice.created_at.to_date %></td>
            </tr>
          <% end %>
        <% else %>
          <tr>
            <td colspan="6"><%= t(:no_data) %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
      <div id="sl_bottom_menu">
        <%= paginate @notices %>
      </div>
    </div>
  </div>
  <% if admin_signed_in? %>
  <div class="col-12">
    <%=link_to t(:link_new),new_notice_path,class: 'btn btn-primary btn-large' %>
  </div>
    <% end  %>
</div>

app/views/notices/_index_media.html.erb
<article class="notice col-12">
  <div class="row">
    <div class="col-7 col-sm-12">
      <h3><%= link_to notice.title, notice_path(notice) %></h3>
    </div>
  </div>
</article>

app/views/notices/_search_form.html.erb
<div class="col-12">
<%=form_tag notices_path,{method:'get'} do %>
  <input type="hidden" name="search" value="1">
    <%
      search_params={search_detail:true}

      aa_class='nav-link'
      if @notice_category.present?
        search_params[:category]=@notice_category
      else
        aa_class+=' active'
      end
      %>
  <%=link_to notices_path(search_params),id: "search-detail" do %><span class="material-icons">search</span><%=t(:search) %><% end  %>
  <!-- <%=submit_tag t(:search),class: 'btn btn-primary btn-block btn-search' %> -->
  <% end %>
</div>

app/views/notices/_search_form_detail.html.erb
<div class="col-12">
  <div class="card">
    <div class="card-body" style="margin-bottom:10px">
      <div class="form-row">
        <div class="col-12" style="margin-bottom:20px">
      <h3 class="float-start">상세검색</h3>
      <%=form_tag blogs_path,:method => 'get', :class=>"float-right" do %>
        <input type="hidden" name="search_summary" value="1">
        <% if @blog.present? %>
          <input type="hidden" name="product" value="<%=@blog.id %>">
        <% else %>
          <%  if @notice_category.present? %>
            <input type="hidden" name="category" value="<%=@notice_category.id %>">
          <% end %>
        <% end %>
        <button type="submit" value="close" style="background-color: Transparent;background-repeat:no-repeat;border: none; "><i class="material-icons">close</i></button>
      <% end %>
        </div>
      </div>
      <%=form_tag notices_path,{method:'get', class: 'search_form_show'} do %>
        <input type="hidden" name="search" value="1">
        <div class="form-row">
        </div>
        <div class="form-row">
        </div>


        <%=submit_tag t(:search),class: 'btn btn-primary btn-lg btn-block btn-search' %>
      <% end %>
    </div>
  </div>


</div>

app/views/notices/edit.html.erb
<section id="edit-notice">
  <div class="row">
    <h2 class="col-12 di-title"><%=t(:edit_notice) %></h2>
  </div>
  <div class="row">
    <%= render 'form', notice: @notice %>
  </div>
</section>

app/views/notices/index.html.erb
<% breadcrumb :notices %>
<%
  render_templete='index_default'

  if session[:notice_list_type].present?
    if session[:notice_list_type]=='list'
      render_templete='index_list'
    end
  end

%>
<div id="notices">
  <div class="row">
    <div class="col-12">
      <ul class="type-selector">
        <li><%=link_to url_for(list_type: 'list') do %><span class="material-icons">view_list</span><% end %></li>
        <li><%=link_to url_for(list_type: 'module') do %><span class="material-icons">view_module</span><% end %></li>
      </ul>
    </div>
    <div class="col-12">
      <h2 class="float-start hidden-title"><%= t(:notice,scope: [:activerecord,:models]) %></h2>
      <div class="float-end">
        <p class="summary text-end">
          <span id="list_count" style="display:none"><%= @notice_count %></span>
          <%= raw t(:there_are_n_notices, count: @notice_count) %>
        </p>
      </div>
    </div>
  </div>
  <%=render render_templete %>
</div>

app/views/notices/new.html.erb
<section id="new-notice">
  <div class="row">
    <h2 class="col-12 di-title"><%=t(:new_notice) %></h2>
  </div>
  <div class="row">
    <%= render 'form', notice: @notice %>
  </div>
</section>

app/views/notices/show.html.erb
<% breadcrumb :notice ,@notice %>
<div id="show-notice">
  <div class="row">
    <article class="col-12 mb-3" itemscope itemprop="article" itemtype="http://schema.org/Article">
      <div class="sl_content_header">
        <h3 itemprop="name"><%= @notice.title %></h3>
        <p class="text-end"><%= t(:created_at, scope: [:activerecord, :attributes, :notice]) %> : <%= I18n.l @notice.created_at.to_date, :format => :long %></p>
      </div>
      <div class="sl_content_main">
        <div class="sl_content_text" itemprop="text"><%=simple_format sanitize(@notice.content.to_s.gsub(/\n/, '<br />'), :tags => %w(br img a)) %></div>

      </div>
    </article>
  </div>
  <div class="row">
    <div class="col-12">
    </div>
  </div>
  <div class="row">
    <div class="btn-group btn-group-lg col-12" role="group" style="margin-top:3rem">
      <%=link_to t(:link_list),notices_path,{class: 'btn btn-secondary btn-large btn-block'} %>
    </div>
  </div>
</div>
<% content_for :json_ld do %>
  <script type="application/ld+json">
    <%= raw(JSON.pretty_generate(json_ld_for_notice(@notice))) %>
  </script>
<% end %>