config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  get 'home/demo', to: 'home#demo'
  get '/privacy', to: 'home#privacy'
  get 'feed',:to=>'home#feed'

  # Admin 인증 라우트
  devise_for :admins,
             class_name: 'User',
             path: 'admins',
             path_names: {
               sign_in: 'login',
               sign_out: 'logout'
             },
             controllers: {
               sessions: 'admins/sessions'
             }

  namespace :admin do
    root to: 'home#index'

    resources :contacts
    resources :users
    resources :blogs
    resources :notices
    resources :histories
    resources :galleries
  end

  devise_for :users, :controllers => { :sessions => "users/sessions",:registrations => "users/registrations" }, :path_names =>  {:sign_up=>'new',:sign_in => 'login', :sign_out => 'logout'}

  devise_scope :user do
    get '/login', to: 'users/sessions#new', as: :login_redirect
    delete '/logout', to: 'users/sessions#destroy', as: :logout_redirect
  end

  resources :intro, :galleries, :blogs, :notices, :locations, :histories, :contacts

end

app/models/history.rb
class History < ActiveRecord::Base
  validates_presence_of :year, :title
end

app/controllers/admin/histories_controller.rb
class Admin::HistoriesController < Admin::AdminController
  before_action :set_history, only: [:show, :edit, :update, :destroy]

  # GET /histories
  # GET /histories.json
  def index
    params[:per_page] = 10 unless params[:per_page].present?

    @history_count = History.count
    @histories = History.page(params[:page]).per(params[:per_page]).order('id desc')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @histories }
    end
  end

  # GET /histories/1
  # GET /histories/1.json
  def show
  end

  # GET /histories/new
  # GET /histories/new.json
  def new
    @history = History.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @history }
    end
  end

  # GET /histories/1/edit
  def edit
  end

  # POST /histories
  # POST /histories.json
  def create
    @history = History.new(history_params)

    respond_to do |format|
      if @history.save
        format.html { redirect_to admin_history_url(@history), :notice => @controller_name + t(:message_success_create) }
        format.json { render :json => @history, :status => :created, :location => @history }
      else
        format.html { render :action => "new" }
        format.json { render :json => @history.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /histories/1
  # PUT /histories/1.json
  def update
    respond_to do |format|
      if @history.update_attributes(history_params)
        format.html { redirect_to admin_history_url(@history), :notice => @controller_name + t(:message_success_update) }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @history.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /histories/1
  # DELETE /histories/1.json
  def destroy
    @history.destroy

    respond_to do |format|
      format.html { redirect_to admin_histories_url }
      format.json { head :ok }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_history
    @history = History.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def history_params
    params.require(:history).permit(:year, :title, :content).merge(user_id: current_user.id)
  end
end

app/controllers/histories_controller.rb
class HistoriesController < ApplicationController
  before_action :authenticate_user!, :except => [:index,:show]
  before_action :set_history, only: [:show, :edit, :update, :destroy]

  def initialize(*params)
    super(*params)

    @application_name=t(:application_name)
    @controller_name= t(:history, scope: [:activerecord, :models])
    @title=@controller_name
  end

  # GET /histories
  # GET /histories.json
  def index
    @histories = History.order('year desc,month desc').page(params[:page]).per(20)
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @histories }
    end
  end

  # GET /histories/1
  # GET /histories/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @history }
    end
  end

  # GET /histories/new
  # GET /histories/new.json
  def new
    @history = History.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @history }
    end
  end

  # GET /histories/1/edit
  def edit
  end

  # POST /histories
  # POST /histories.json
  def create
    @history = History.new(history_params)

    respond_to do |format|
      if @history.save
        format.html { redirect_to histories_path, :notice=> @controller_name +t(:message_success_create)}
        format.json { render json: @history, status: :created, location: @history }
      else
        format.html { render action: "new" }
        format.json { render json: @history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /histories/1
  # PUT /histories/1.json
  def update
    respond_to do |format|
      if @history.update_attributes(history_params)
        format.html { redirect_to histories_path, :notice=> @controller_name +t(:message_success_update)}
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /histories/1
  # DELETE /histories/1.json
  def destroy
    @history.destroy

    respond_to do |format|
      format.html { redirect_to histories_path }
      format.json { head :no_content }
    end
  end
  
  private
  # Use callbacks to share common setup or constraints between actions.
  def set_history
    @history = History.find(params[:id])
  end
  
  # Never trust parameters from the scary internet, only allow the white list through.
  def history_params
    params.require(:history).permit(:year, :title, :content).merge(user_id: current_user.id)
  end  
end

app/views/histories/_form.html.erb
<%= form_for @history do |f| %>
	<% if @history.errors.any? %>
	<div id="error_explanation">
		<h2><%= pluralize(@notice.errors.count, "error") %> prohibited this notice from being saved:</h2>
		<ul>
			<% @history.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
	<% end %>
	<div class="form-group">
		<%= f.label :year, class: 'form-label fs-5' %><br />
		<%= f.select :year, options_for_select((Date.current.year - 100..Date.current.year).to_a.reverse, f.object.year), {}, class: 'form-control form-control-lg', required: true %>
	</div>
	<div class="form-group">
		<%= f.label :month, class: 'form-label fs-5' %><br />
		<%= f.select :month, options_for_select([["필요하면 선택하세요", ""]] + (1..12).map { |m| [m, m] }, f.object.month), {}, class: 'form-control form-control-lg' %>
	</div>
	<div class="form-group">
		<%= f.label :title, class: 'form-label fs-5' %><br />
		<%= f.text_field :title, :class=>'form-control form-control-lg', :required=>'required' %>
	</div>
	<div class="form-group">
		<%= f.label :content, class: 'form-label fs-5' %><br />
		<%= f.text_area :content, :class=>'form-control form-control-lg', :required=>'required', :id => "sl_content" %>
	</div>
	<div class="d-grid gap-2">
		<%= f.submit :class => 'btn btn-lg btn-primary' %>
	</div>
<% end %>

app/views/histories/edit.html.erb
<section id="sl_history_edit">
	<%= render 'form' %>
	<%= link_to t(:link_show), @history %> |
	<%= link_to t(:link_list), histories_path %>
</section>

app/views/histories/index.html.erb
<% breadcrumb :histories %>
<section id="sl_history_index">
		<h2>약력</h2>
			<% unless @histories.empty? %>
			<% @histories.each do |history| %>
			<article class="media p-3 p-lg-5 rounded-4 lh-lg mb-3">
				<dl>
			<dt>
				<%=history.year %><%=t(:year) %>
				<% if history.month %>
				<%= history.month %><%=t(:month) %>
				<% end %>
			</dt>
			<dd>

				<b><%=history.title %></b>
				<%=simple_format(history.content) %>
			<% if user_signed_in? %>
			<% if current_user.admin? %>
				<div class="history_menu">
					<%= link_to t(:link_edit), edit_history_path(history) %> &nbsp; | &nbsp; <%= link_to t(:link_delete), history, method: :delete, data: { confirm: t(:delete_confirm) } %>
				</div>
			<% end %>
			<% end %>
				</dd>
			</article>
			<% end %>
			<% end %>
	<% if admin_signed_in? %>
		<%= link_to t(:link_new), new_history_path %>
	<% end %>
</section>

app/views/histories/new.html.erb
<section id="sl_history_new">
	<%= render 'form' %>
	<%= link_to t(:link_list), histories_path %>
</section>

app/views/histories/show.html.erb
<% if notice %>
<%= render :partial => 'layouts/notice',:locals=>{:notice=>notice} %>
<% end %>
<section id="sl_history_show">
	<div class="slboard_content">
		<div class="sl_content_header">
			<h3><%= @notice.title %></h3>
			<p><%=t(:label_name) %> :<%= @notice.user.name %>&nbsp;&nbsp;&nbsp; <%=t(:label_creatd_at) %> : <%= @notice.created_at %></p>
		</div>
		<div class="sl_content_main">
			<div class="sl_content_text"><%= simple_format(@notice.notice_content.content) %></div>
		</div>
	</div>
	<div id="sl_content_bottom_menu">
		<%= link_to t(:link_list),notices_path %>
		<% if user_signed_in? %>
		<% if current_user.admin? %>
		&nbsp; | &nbsp; <%= link_to t(:link_edit), edit_notice_path(@notice) %> &nbsp; | &nbsp; <%= link_to t(:link_delete), @notice, method: :delete, data: { confirm: t(:delete_confirm)} %>
		<% end %>
		<% end %>
	</div>
</section>