config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  get 'home/demo', to: 'home#demo'
  get '/privacy', to: 'home#privacy'
  get 'feed',:to=>'home#feed'

  # Admin 인증 라우트
  devise_for :admins,
             class_name: 'User',
             path: 'admins',
             path_names: {
               sign_in: 'login',
               sign_out: 'logout'
             },
             controllers: {
               sessions: 'admins/sessions'
             }

  namespace :admin do
    root to: 'home#index'

    resources :contacts
    resources :users
    resources :blogs
    resources :notices
    resources :histories
    resources :galleries
  end

  devise_for :users, :controllers => { :sessions => "users/sessions",:registrations => "users/registrations" }, :path_names =>  {:sign_up=>'new',:sign_in => 'login', :sign_out => 'logout'}

  devise_scope :user do
    get '/login', to: 'users/sessions#new', as: :login_redirect
    delete '/logout', to: 'users/sessions#destroy', as: :logout_redirect
  end

  resources :intro, :galleries, :blogs, :notices, :locations, :histories, :contacts

end

app/models/notice.rb
class Notice < ActiveRecord::Base
  is_impressionable
  has_rich_text :content
  validates_presence_of :title
  validates_length_of :title, minimum: 4, maximum: 60
  belongs_to :user, :autosave=>true
end

app/controllers/admin/notices_controller.rb
class Admin::NoticesController < Admin::AdminController
  before_action :set_notice, only: [:show, :edit, :update, :destroy]

  # GET /notices
  # GET /notices.json
  def index
    params[:per_page] = 10 unless params[:per_page].present?

    @notice_count = Notice.count
    @notices = Notice.page(params[:page]).per(params[:per_page]).order('id desc')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @notices }
    end
  end

  # GET /notices/1
  # GET /notices/1.json
  def show
  end

  # GET /notices/complete
  def new
    @notice = Notice.new
  end

  # GET /notices/1/edit
  def edit
  end

  # POST /notices
  # POST /notices.json
  def create
    @notice = Notice.new(notice_params)

    respond_to do |format|
      if @notice.save
        format.html { redirect_to [:admin, @notice], notice: t(:notice, scope: [:activerecord, :models])+t(:message_success_create) }
        format.json { render :show, status: :created, location: @notice }
      else
        format.html { render action: 'new' }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notices/1
  # PATCH/PUT /notices/1.json
  def update
    respond_to do |format|
      if @notice.update(notice_params)
        format.html { redirect_to [:admin, @notice], notice: t(:notice, scope: [:activerecord, :models])+t(:message_success_update) }
        format.json { render :show, status: :ok, location: @notice }
      else
        format.html { render action: 'edit' }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notices/1
  # DELETE /notices/1.json
  def destroy
    @notice.destroy
    respond_to do |format|
      format.html { redirect_to admin_notices_url }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_notice
    @notice = Notice.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def notice_params
    params.require(:notice).permit(:title, :popup, :enable, :content).merge(user_id: current_user.id)
  end
end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController
  impressionist :actions => [:show]
  before_action :authenticate_user!, :except => [:index,:show]
  before_action :set_notice, only: [:show, :edit, :update, :destroy]

  def initialize(*params)
    super(*params)

    @application_name=t(:application_name)
    @controller_name= t(:notice, scope: [:activerecord, :models])
    @title=@controller_name
  end
  # GET /notices
  # GET /notices.json
  def index
    if params[:search_detail].present?
      session[:search_detail]=1
    else
      if params[:search_summary].present?
        session.delete(:search_detail)
      end
    end

    if params[:list_type].present?
      if params[:list_type]=='list'
        session[:notice_list_type]='list'
      else
        session[:notice_list_type]='module'
      end
    end


    condition = { enable: true }

    @notice_count = Notice.where(condition).count
    @notices = Notice.where(condition).page(params[:page]).per(params[:per_page]).order('id desc')


    respond_to do |format|
      format.html # _slide.html.erb
      format.json { render json: @notices }
    end
  end

  # GET /notices/1
  # GET /notices/1.json
  def show
  end

  # GET /notices/complete
  def new
    @notice = Notice.new
  end

  # GET /notices/1/edit
  def edit
  end

  # POST /notices
  # POST /notices.json
  def create
    @notice = Notice.new(notice_params)

    respond_to do |format|
      if @notice.save
        format.html { redirect_to [ @notice], notice: t(:notice, scope: [:activerecord, :models])+t(:message_success_create) }
        format.json { render :show, status: :created, location: @notice }
      else
        format.html { render action: 'new' }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notices/1
  # PATCH/PUT /notices/1.json
  def update
    respond_to do |format|
      if @notice.update(notice_params)
        format.html { redirect_to [ @notice], notice: t(:notice, scope: [:activerecord, :models])+t(:message_success_update) }
        format.json { render :show, status: :ok, location: @notice }
      else
        format.html { render action: 'edit' }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /notices/1
  # DELETE /notices/1.json
  def destroy
    @notice.destroy
    respond_to do |format|
      format.html { redirect_to admin_notices_url }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_notice
    @notice = Notice.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def notice_params
    params.require(:notice).permit(:title, :popup, :enable, :content).merge(user_id: current_user.id)
  end
end

app/views/admin/notices/_form.html.erb
<%= form_with(model: [:admin, notice], local: true, data: { turbo_frame: "_top" }) do |form| %>
  <% if notice.errors.any? %>
    <div id="error_explanation" class="alert alert-danger">
      <a href="#" class="close" data-dismiss="alert">&times;</a>
      <h2><%= pluralize(notice.errors.count, "개의 문제") %>로 진행할 수 없습니다.</h2>
      <ul>
        <% notice.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="card">
    <div class="card-body">
      <!-- <div class="form-group">
        <%= form.label :user_id, "사용자" %>
        <%= form.text_field :user_nickname,
                            class: 'form-control',
                            readonly: true,
                            data: {
                              "user-selector-target": "input",
                              "bs-toggle": "modal",
                              "bs-target": "#userSelectorModal"
                            } %>
        <%= form.hidden_field :user_id, data: { "user-selector-target": "hiddenInput" } %>
      </div> -->
      <div class="form-group">
        <%= form.label :title %>
        <%= form.text_field :title, :class => 'form-control', :required => 'required' %>
      </div>
      <div class="form-group">
        <%= form.label :content %>
        <%= form.rich_text_area :content %>
      </div>
    </div>
    <div class="form-group">
      <%= form.label :enable %>
      <%= form.check_box :enable %>
    </div>
  </div>
  <div class="d-grid gap-2">
    <%= form.submit :class => "btn btn-primary btn-block btn-lg" %>
  </div>
<% end %>

app/views/admin/notices/_nav.html.erb
<%
    a_class = 'nav-link'
    b_class = 'nav-link'
    c_class = 'nav-link'
    d_class = 'nav-link'

    if params[:controller] == 'admin/blogs'
      a_class += ' active'
    end

    if params[:controller] == 'admin/galleries'
      b_class += ' active'
    end

    if params[:controller] == 'admin/histories'
      c_class += ' active'
    end

    if params[:controller] == 'admin/notices'
      d_class += ' active'
    end


  %>
  <div class="col-12">
    <nav class="sub-nav">
      <ul class="nav nav-pills">
        <li class="nav-item"><%= link_to t(:blog, scope: [:activerecord, :models]), admin_blogs_path, { :class => a_class } %></li>
        <li class="nav-item"><%= link_to t(:gallery, scope: [:activerecord, :models]), admin_galleries_path, { :class => b_class } %></li>
        <li class="nav-item"><%= link_to t(:history, scope: [:activerecord, :models]), admin_histories_path, { :class => c_class } %></li>
        <li class="nav-item"><%= link_to t(:notice, scope: [:activerecord, :models]), admin_notices_path, { :class => d_class } %></li>
      </ul>
    </nav>
  </div>

app/views/admin/notices/edit.html.erb
<section id="edit-notice" class="col-12">
  <div class="row">
    <h2 class="col-12"><%= t(:edit_notice) %></h2>
  </div>
  <div class="row">
    <div class="col-12">
      <%= render 'form', notice: @notice %>
    </div>
  </div>
</section>

app/views/admin/notices/index.html.erb
<div class="col-12">
  <h2 class="float-left hidden-title"><%= t(:notice_list) %></h2>
      <div class="float-right">
        <p class="summary">
          <span id="list_count" style="display:none"><%=@notice_count %></span>
          <%=raw t(:there_are_n_notices,count: @notice_count) %>
        </p>
      </div>
    </div>
    <article class="col-12">
      <table id="prepare_list" class="table table-striped table-hover">
        <colgroup>
          <col style="width:120px">
          <col>
          <col>
          <col style="width:210px">
          <% if can?(:update, Notice) || can?(:delete, Notice) %>
            <col<%=manage_width(Notice) %>>
          <% end %>
        </colgroup>
        <thead class="thead-default">
        <tr>
          <th class="text-center"><%= t(:enable,scope:[:activerecord,:attributes,:notice]) %></th>
          <th><%= t(:title,scope:[:activerecord,:attributes,:notice]) %></th>
          <th><%= t(:count,scope:[:activerecord,:attributes,:notice]) %></th>
          <th class="text-right"><%= t(:created_at,scope:[:activerecord,:attributes,:notice]) %></th>
          <% if can?(:update, Notice) || can?(:delete, Notice) %>
            <th class="text-center"><%= t(:manage) %></th>
          <% end %>
        </tr>
        </thead>
        <tbody>
        <% unless @notice_count.zero? %>
          <% @notices.each_with_index do |notice,index| %>
            <tr>
              <td>
                <div class="form-check form-switch">
                  <input
                    class="form-check-input"
                    type="checkbox"
                    id="notice_display<%= index %>"
                    value="<%= notice.id %>"
                    <% if notice.enable %> checked <% end %>
                  >
                  <label class="form-check-label" for="notice_display<%= index %>">
                    <% if notice.enable %> <%= t(:display) %> <% else %> <%= t(:hidden) %> <% end %>
                  </label>
                </div>
              </td>
              <td><%= link_to notice.title,admin_notice_path(notice) %></td>
              <td class="text-right"><%= notice.impressionist_count(:filter => :ip_address) %></td>
              <td class="text-right"><%= I18n.l notice.created_at.to_date, :format => :long %></td>
              <% if can?(:update, notice) or can?(:delete, notice) %>
                <td class="text-right">
                  <% if can? :update, notice %>
                    <%= link_to edit_admin_notice_path(notice), :class => "btn btn-secondary" do %>
                      <%= t(:edit) %>
                    <% end %>
                  <% end %>
                  <% if can? :delete, notice %>
                    <%= link_to admin_notice_path(notice), :method => :delete, :data => { :confirm => t(:delete_confirm) }, :class => "btn btn-danger" do %>
                      <%= t(:delete) %>
                    <% end %>
                  <% end %>
                </td>
              <% end %>
            </tr>
          <% end %>
        <% else %>
          <tr>
            <td colspan="4" class="text-center"><%= t(:no_data) %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
      <div class="pagination justify-content-center">
        <%= paginate @notices %>
      </div>
      <%= link_to t(:add), new_admin_notice_path, :class => "btn btn-primary" %>
    </article>

app/views/admin/notices/new.html.erb
<section id="new-notice" class="col-12">
  <div class="row">
    <h2 class="col-12"><%= t(:new_notice) %></h2>
  </div>
  <div class="row">
    <div class="col-12">
      <%= render 'form', notice: @notice %>
    </div>
  </div>
</section>

app/views/admin/notices/show.html.erb
<section id="show-notice" class="col-12">
  <div class="row">
    <div class="col-12">
      <article class="card">
        <h3 class="card-header"><%=@notice.title %></h3>
        <div class="card-body">
          <dl>
            <dt><%= t(:created_at, scope: [:activerecord, :attributes, :product]) %></dt>
            <dd><%= I18n.l @notice.created_at.to_date, :format => :long %></dd>
            <dt><%= t(:updated_at, scope: [:activerecord, :attributes, :product]) %></dt>
            <dd><%= I18n.l @notice.updated_at.to_date, :format => :long %></dd>
          </dl>
        </div>
      </article>
    </div>
  </div>
  <div class="row">
    <div class="col-12 col-xl-6">
      <%= link_to t(:link_list), admin_notices_path, class: 'btn btn-secondary' %>
    </div>
    <div class="col-12 col-xl-6 text-right">
      <%= link_to t(:edit), edit_admin_notice_path(@notice), class: 'btn btn-secondary' %>
      <%= link_to t(:delete), admin_notice_path(@notice), :method => :delete, :data => { :confirm => t(:delete_confirm) }, class: 'btn btn-danger' %>
    </div>
  </div>
</section>